### ISSUE TITLE
How to use FDFD to Simulate TE to TM mode converter

### ISSUE THREAD

**Issue by JeremieMelo** [google/ceviche-challenges#7]
Hi, is it possible to use FDFD (ceviche) to simulate or perform inverse design on TE to TM mode converter? I noticed for FDTD, there are 6 fields, but in FDFD, it only has 3 fields for pure TE (Hx, Hy, Ez) or pure TM (Ex, Ey, Hz). Any suggestions on how to use FDFD to simulate TE-TM mode conversion? Thank you. Any material or examples are appreciated.

**Comment by ianwilliamson** [comment]
No, this type of device is not possible to simulate or optimize in Ceviche because it only supports 2D geometry.

Note that the pure TM / TE modes are from the geometry symmetry (2D vs 3D) rather than the frequency / time domain (FDFD vs FDTD). In 2D, the TM and TE solutions are completely decoupled and independent from each other. In a 3D geometry it is never possible to obtain purely TM / TE modes, but you can build converters between the *mostly* TM / TE modes.
